#!/bin/bash

# requiring 2nd arg as the required cloud provider for the project
CLOUD_PROVIDER=$1 
if  [[ -z $CLOUD_PROVIDER ]]; then
    echo "Required arg: CLOUD_PROVIDER"
    return
fi

# requiring 3rd arg as the requested name of the project
PROJECT_NAME=$2 
if  [[ -z $PROJECT_NAME ]]; then
    echo "Required arg: PROJECT_NAME"
    return
fi

# create the project dir and cd into it
PROJECT_DIR="./$CLOUD_PROVIDER/$PROJECT_NAME"
mkdir $PROJECT_DIR
cd $PROJECT_DIR

# create the basic terraform files that are typically used in a project
touch main.tf
touch vairables.tf
touch terraform.tfvars
